mask_dir: /home/local/eda13/gc29434/phd/intern/DiffOPC/benchmark/baseline/multilevel/mask
target_dir: /home/local/eda13/gc29434/phd/intern/DiffOPC/benchmark/baseline/multilevel/target
rect_shape_w: 2048
rect_shape_h: 2048
min_area: 400
min_wh: 3
exp_folder: ./aim-mrc
exp_name: mrc
