Iterations: 1
TargetDensity: 0.225
SigmoidSteepness: 4.0
WeightEPE: 0.5
WeightL2: 1.0
WeightPVBL2: 0.5
WeightPVBand: 0.0
StepSize: 1

TileSizeX: 2048
TileSizeY: 2048
OffsetX: 512
OffsetY: 512
ILTSizeX: 1024
ILTSizeY: 1024
SEG_LENGTH: 60
VISUAL_DEBUG: 0
VERBOSE: 1
Evaluation: 1
