Iterations: 5
TargetDensity: 0.225
SigmoidSteepness: 4.0
WeightEPE: 0.5
WeightL2: 1.0
WeightPVBL2: 0.5
WeightPVBand: 0.0
StepSize: 1

OPT: "adam" # 'adam' or 'sgd'

TileSizeX: 2048
TileSizeY: 2048
OffsetX: 512
OffsetY: 512
ILTSizeX: 1024
ILTSizeY: 1024
SEG_LENGTH: 60
DownScale: 1

# SRAF parameters
IsInsertSRAF: false
SRAF_FORBIDDEN: 40
SRAF_ITERATIONS: 4
SRAF_threshold_min: 0.2
SRAF_contour_area: 400
SRAF_min_contour_wh_rule: 20
SRAF_initial_sraf_wh: 60

VISUAL_DEBUG: 1
VERBOSE: 1

Evaluation: 1
