common:
  TargetDensity: 0.225
  SigmoidSteepness: 4.0
  WeightEPE: 0.5
  WeightL2: 1.0
  WeightPVBL2: 0.5
  WeightPVBand: 0.0
  StepSize: 1
  OPT: "adam" # 'adam' or 'sgd'

low:
  # common parameters
  TargetDensity: ${common.TargetDensity}
  SigmoidSteepness: ${common.SigmoidSteepness}
  WeightEPE: ${common.WeightEPE}
  WeightL2: ${common.WeightL2}
  WeightPVBL2: ${common.WeightPVBL2}
  WeightPVBand: ${common.WeightPVBand}
  StepSize: ${common.StepSize}
  OPT: ${common.OPT}
  # Debug parameters
  VISUAL_DEBUG: ${common.VISUAL_DEBUG}
  VERBOSE: ${common.VERBOSE}

  Iterations: 80
  DownScale: 4
  TileSizeX: 512
  TileSizeY: 512
  OffsetX: 96
  OffsetY: 96
  ILTSizeX: 320
  ILTSizeY: 320
  SEG_LENGTH: 15

  # SRAF parameters
  IsInsertSRAF: False
  SRAF_FORBIDDEN: 10
  SRAF_ITERATIONS: 70
  SRAF_threshold_min: 0.2
  SRAF_contour_area: 25
  SRAF_min_contour_wh_rule: 5
  SRAF_initial_sraf_wh: 15

mid:
  # common parameters
  TargetDensity: ${common.TargetDensity}
  SigmoidSteepness: ${common.SigmoidSteepness}
  WeightEPE: ${common.WeightEPE}
  WeightL2: ${common.WeightL2}
  WeightPVBL2: ${common.WeightPVBL2}
  WeightPVBand: ${common.WeightPVBand}
  StepSize: ${common.StepSize}
  OPT: ${common.OPT}
  # Debug parameters
  VISUAL_DEBUG: ${common.VISUAL_DEBUG}
  VERBOSE: ${common.VERBOSE}

  Iterations: 80
  DownScale: 2
  TileSizeX: 1024
  TileSizeY: 1024
  OffsetX: 192
  OffsetY: 192
  ILTSizeX: 640
  ILTSizeY: 640
  SEG_LENGTH: 30

  # SRAF parameters
  IsInsertSRAF: true
  SRAF_FORBIDDEN: 20
  SRAF_ITERATIONS: 70
  SRAF_threshold_min: 0.2
  SRAF_contour_area: 100
  SRAF_min_contour_wh_rule: 10
  SRAF_initial_sraf_wh: 30

high:
  # common parameters
  TargetDensity: ${common.TargetDensity}
  SigmoidSteepness: ${common.SigmoidSteepness}
  WeightEPE: ${common.WeightEPE}
  WeightL2: ${common.WeightL2}
  WeightPVBL2: ${common.WeightPVBL2}
  WeightPVBand: ${common.WeightPVBand}
  StepSize: ${common.StepSize}
  OPT: ${common.OPT}
  # Debug parameters
  VISUAL_DEBUG: ${common.VISUAL_DEBUG}
  VERBOSE: ${common.VERBOSE}

  Iterations: 80
  DownScale: 1
  TileSizeX: 2048
  TileSizeY: 2048
  OffsetX: 384
  OffsetY: 384
  ILTSizeX: 1280
  ILTSizeY: 1280
  SEG_LENGTH: 60

  # SRAF parameters
  IsInsertSRAF: true
  SRAF_FORBIDDEN: 40
  SRAF_ITERATIONS: 70
  SRAF_threshold_min: 0.2
  SRAF_contour_area: 400
  SRAF_min_contour_wh_rule: 20
  SRAF_initial_sraf_wh: 60
